### PR TITLE
initial code for changing the language

### LINKED ISSUE #1: Internationalization
Since Jupyterlab and Blockly support translations and localization would be excellent to support it on the extension.

Some documentation to get started:
* [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/extension/internationalization.html)
* [Blockly](https://developers.google.com/blockly/guides/configure/web/translations)

The idea would be to add the dependency `ITranslator` from JupyterLab, listen to the translator and when it changes, load the corresponding language in blockly or default to English in case the language is not supported.

> Note: I'm not sure if we can listen for changes in the `ITranslator` or if there is a way to know what language is loaded in Lab.

For how to import the `ITranslator` and load it, see the following example:
https://github.com/jupyterlab/extension-examples/blob/8bc09d2839efed8078c9fbc43da0fd39a0b7d0a3/signals/src/index.ts#L55

For every other UI feature, we add to the extension, we need to add the labels using `trans.__('Label Example');`, see:
https://github.com/jupyterlab/extension-examples/blob/8bc09d2839efed8078c9fbc43da0fd39a0b7d0a3/signals/src/index.ts#L81

### PR DESCRIPTION
**Pull request by DenisaCG**
The PR is missing the logic for listening to language changes, in Jupyter Lab.

It also mentions [this issue](https://github.com/google/blockly/issues/5818), in connection with the error for using the _setLocale_ property from Blockly.

### CODE REVIEW

**Comment by hbcarlos** [comment]
I believe we can not listen for changes on the `ITranslator`. But there is probably another solution. I saw the language is stored in the settings, we can use the settings to listen for changes in language.

image

There is here an example of how to use the settings that could be useful.
https://github.com/jupyterlab/extension-examples/tree/master/settings

And this is the `ITraslation` plugging, it could be useful to see what is the name of the plugin and the name of the settings we want to listen to for changes.
https://github.com/jupyterlab/jupyterlab/blob/29b6cc783a8e3169385df5cc452cf30975c41e4e/packages/translation-extension/src/index.ts#L38-L40

**Comment by hbcarlos** [comment]
Hi @DenisaCG the PR looks great!
Do you mind rebasing to resolve the conflicts?
I just realize that Blockly languages are javascript modules and would be better to load them dynamically. I opened a PR to your branch as an example of how to load them dynamically.
https://github.com/DenisaCG/jupyterlab-blockly/pull/3

**Comment by hbcarlos** [comment]
Thanks for this awesome feature @DenisaCG!
I added a couple of commits to fix the CI. We have TypeScript configured to prevent using `@ts-ignore` but we need to use it because Blockly is missing some types, I just added this commit https://github.com/QuantStack/jupyterlab-blockly/pull/18/commits/9f456a226480e7c8c49e074543176a47a27fde9a to allow the `@ts-ignore` in line 180.

**Comment by DenisaCG** [comment]
Thank you for the great feedback and help @hbcarlos! 

As a wrap-up, in `index.ts`, we used `locale` from the `ISettingsRegistry` to listen to the changes in language from JupyterLab: https://github.com/QuantStack/jupyterlab-blockly/blob/d56ccaff8e583a8016eeb6c1025b46e670ea320c/src/index.ts#L120-L144. 

Further, in `manager.ts` we used dynamic imports to include all the language modules from Blockly and load the respective language each user is using, in accordance to the Jupyter Lab one: https://github.com/QuantStack/jupyterlab-blockly/blob/d56ccaff8e583a8016eeb6c1025b46e670ea320c/src/manager.ts#L68-L183.

**Pull request merged**
